spring:
  profiles:
    # 激活的配置
    active: dev
  # 终端彩色输出信息
  output.ansi.enabled: ALWAYS
  resources:
    # 不映射工程中的静态资源文件比如：html、css
    # 如果某些情况需要映射
    # 比如 swagger2，可以在 addResourceHandlers 和 addViewControllers 中特别添加，参考 WebMvcConfig
    add-mappings: false
  mvc:
    # 当出现 404 错误时，直接抛出异常（默认是显示一个错误页面）
    throw-exception-if-no-handler-found: true
  freemarker:
    # 关闭模版检查
    checkTemplateLocation: false

rsa:
  # 私钥
  private-key: MIIBVAIBADANBgkqhkiG9w0BAQEFAASCAT4wggE6AgEAAkEArD4P1yMYRsS4YSEbB7V3LQs/+6MrTbAdnlF8CdangeD89gRrp9sz8MutI1s2xOPnpavSv8HeB3VpwE1Iw1WK2QIDAQABAkB4wFWolJD7ZASDC4uAnwZ6zK1Bg8XjA/nvuN6Fozfxw5s40HSPyild32CX47fCOYlt94shRrNaIHIN78N8+ioVAiEA4hWDEnzyqT1mkrLCdgVNnH36aow3/jonp0trQpSagKcCIQDDCLEDfjcPUovDkp9XQZ3LlYU8+zPGJ9Nccck0YtGIfwIhAOGGcgScTXhTfqGx3lfavGvyIz3r9+MLYgj5K9rz4BebAiB4CAtZSP598aGO1dg3DW0d9IGxzDBLDguo42afVQn75QIgBy9s8n1ZyWyLloCBb4+Wf0iTOUJC7II9Xq1LUF2QJGo=
  # 公钥
  public-key: MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAKw+D9cjGEbEuGEhGwe1dy0LP/ujK02wHZ5RfAnWp4Hg/PYEa6fbM/DLrSNbNsTj56Wr0r/B3gd1acBNSMNVitkCAwEAAQ==

jasypt:
  encryptor:
    # 自定义的加密器
    bean: myStringEncryptor
    # 自定义被加密值的发现器
    property:
      detector-bean: myEncryptablePropertyDetector
    # 先 RSA，后 Base64 加密的密码
    # 在 JasyptConfig#myStringEncryptor 中先解密后再使用
    password: fnMa4sWpCFSG1Wl3+tkjSRKfdApiZBGms5NE75TqzudMq1/9py5uvKk7urU4dKnuV+3/Tq69Y2E4gohJlAD3cA==

mybatis:
  # 存放实体的位置
  type-aliases-package: com.yly.crm.entity
  # 存放 mapper 映射文件的位置
  mapper-locations: classpath:mapper/*.xml



# 分页插件
# https://github.com/pagehelper/Mybatis-PageHelper/blob/master/wikis/zh/HowToUse.md
pagehelper:
  # pageSize=0 时查出所有结果，相当于没分页
  page-size-zero: true
  # 数据库方言
  helperDialect: mysql
  # 分页合理化
  # pageNum <= 0 时会查询第一页
  # pageNum > pages（超过总数时），会查询最后一页
  reasonable: true
  # 支持通过 Mapper 接口参数来传递分页参数
  supportMethodsArguments: true

# 日志
#logging:
#  # 以文件方式记录日志
#  file: yly.crm.log
#  # 设置目录
#  path: /var/log